### ISSUE TITLE
Can you help me 

### ISSUE THREAD

**Issue by 4N4S** [islamgab/Files_Leakage#1]
i'm stuck on this challenge for a while now and even with your writeup i couldn't get the flag by myself , i got all the files and i tried stegcrack some stego tools for wav file but nothing how you figured out the length of the password and how u did get the flag file, this is my email paoipaoi1235@gmail.com

**Comment by islamgab** [comment]
no probem i will update a write up give me 2 day i will send you msg while update

**Comment by islamgab** [comment]
i fix it ok if you found it not easy tell me, thank you

**Comment by 4N4S** [comment]
thanks a lot now it's make sense
